### ISSUE TITLE
UNIQUE not working

### ISSUE THREAD

**Issue by ziorufus** [EnigmaBridge/hibernate4-sqlite-dialect#4]
Hello! I'm using your great Dialect to integrate SQLite into Spring, but it seems that UNIQUE constraints do not work.

This is my code:

```
import javax.persistence.*;

@Entity
@Table(indexes = {
        @Index(name = "insert_time_index", columnList = "insert_time", unique = true),
        @Index(name = "start_time_index", columnList = "start_time"),
        @Index(name = "expired_time_index", columnList = "expired_time")
})
public class Tag {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    private String tag;
    private Long insert_time, start_time, expired_time;
    private Boolean done = false;
    private String next_token = "";

}
It's weird that if I remove the unique property everything works as expected.
```

I've also tried the `uniqueConstraints = @UniqueConstraint(name = "insert_time_index", columnNames = {"insert_time"})` annotation, but with no success.

Am I doing something wrong?

**Comment by ph4r05** [comment]
Thanks for letting us know!

Unfortunately, we do not actively maintain this repository anymore and I don't think I find free time to look into this. So the best bet would be either to wait for a PR (we review and accept those), or try to hack it on your own.

**Comment by ph4r05** [comment]
You may increase chances of getting this fixed by adding log of the problem / exception that happens when you are using Unique constraint.

**Comment by ph4r05** [comment]
My best bet is that https://github.com/EnigmaBridge/hibernate4-sqlite-dialect/blob/607a4bf2031dee8bb061b4434069a4c1bbce1847/src/main/java/com/enigmabridge/hibernate/dialect/SQLiteDialect.java#L332 does not have all required method implemented. Thus the table creation does not work.

It is probably needed to revisit and implement all methods: https://docs.jboss.org/hibernate/orm/5.1/javadocs/org/hibernate/dialect/unique/DefaultUniqueDelegate.html

https://github.com/hibernate/hibernate-orm/blob/0c79d1d644600b5d82614dc21e59e2930103025f/hibernate-core/src/main/java/org/hibernate/dialect/unique/MySQLUniqueDelegate.java#L17

maybe mainly `getColumnDefinitionUniquenessFragment`

**Comment by ziorufus** [comment]
Thank you, I got it work!

**Comment by ph4r05** [comment]
@ziorufus thanks for letting us know! btw how did you fix it pls? maybe also for others tackling the same problem. Thanks!

**Comment by ziorufus** [comment]
I found this updated version of the (same?) project:

```
        <dependency>
            <groupId>com.github.gwenn</groupId>
            <artifactId>sqlite-dialect</artifactId>
            <version>0.1.2</version>
        </dependency>
```
